### ISSUE TITLE
Dependency can not find

### ISSUE THREAD

**Issue by chenhongen** [pschatzmann/smart-EDGAR#1]
![2019-12-03_165834](https://user-images.githubusercontent.com/16499303/70035645-37c0bf80-15ee-11ea-9a77-78fc15f74ec0.png)

**Comment by chenhongen** [comment]
[WARNING] The POM for ch.pschatzmann:smart-edgar:jar:1.0.2-SNAPSHOT is missing, no dependency information available

**Comment by pschatzmann** [comment]
I needed to restart the server. The repository is now available again...

**Comment by chenhongen** [comment]
When I try again,It still failed.（T T）
![000](https://user-images.githubusercontent.com/16499303/70063422-b0da0a00-1622-11ea-909c-95e8f3cac68a.png)

**Comment by pschatzmann** [comment]
I just noticed that LATEST does not work any more. 
The following is working for me:

  <dependencies>    
	<dependency>
		<groupId>ch.pschatzmann</groupId>
		<artifactId>smart-edgar</artifactId>
		<version>1.0.2-SNAPSHOT</version>
	</dependency>
  </dependencies>
  
I am planning to release 1.0.2 soon...

**Comment by chenhongen** [comment]
OK,Waiting for the Release:smile:

**Comment by pschatzmann** [comment]
The version V1.0.2 has been committed today and is available in the repository. You can double check with https://software.pschatzmann.ch/#browse/search=keyword%3Dsmart-edgar
